FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/

HEALTHCHECK --interval=30s --timeout=3s \
 CMD wget --quiet --tries=1 --spider http://localhost/health/ || exit 1